#ifndef KINDMSGDEF_H_
#define KINDMSGDEF_H_


#define PACKET 0
#define END_TRANSMISSION_MSG 1
#define SERVER_CAPACITY_MSG 2
#define CHOOSE_SERVER_MSG 3
#define SWITCH_DELAY_TIMER 4
#define TRANSMISSION_TIME_TIMER 5
#define SELECTION_TARGET_CAPACITY_TIMER 6


#endif /* KINDMSGDEF_H_ */
